services:
  datalchemist:
    image: ookamidock/datalchemist:latest
    ports:
      - "80:80"
    environment:
      - DA_LISTEN=:80
      - DA_DATABASE=/sqlite/datalchemist.sqlite
      - DA_SESSION=3600
      - DA_SECRETKEY_FILE=/run/secrets/datalchemist_secret_key
    restart: always
    volumes:
      - data:/sqlite/
    secrets:
      - source: datalchemist_secret_key
        target: datalchemist_secret_key
        mode: 0400
volumes:
  data:
secrets:
  datalchemist_secret_key:
    file: ./secrets/datalchemist_secret_key
